### ISSUE TITLE
Binaries for Win and MacOS

### ISSUE THREAD

**Issue by Corsten56** [x2bool/egram.tel#7]
Hello.

Looks interesting implementation, thank you.
I'm not familiar with compiling, so can you please provide binaries for Windows and Mac?
Think I'm not only one.

Best regards.

**Comment by x2bool** [comment]
Do you mean compiled version of the app? If you do then I am afraid building apps does not make sense for now. Egram is not yet usable for the real world.

**Comment by Corsten56** [comment]
Ok. Thanks.
Will wait for suitable version.
