### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by Neftedollar** [x2bool/egram.tel#8]
The webpage at https://egram.tel/ might be temporarily down or it may have moved permanently to a new web address.
ERR_NAME_RESOLUTION_FAILED

**Comment by x2bool** [comment]
Hey! This domain is indeed intended for the project. But there is nothing to publish right now. As soon as the more or less stable builds are going to be ready, I will publish them on that site.

**Comment by Neftedollar** [comment]
Ок, thnx.
I's funny)
